package com.github.liuche51.easyTaskX.dto.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NodeDto.proto

public final class NodeDto {
  private NodeDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string host = 1;
    /**
     * <code>optional string host = 1;</code>
     */
    boolean hasHost();
    /**
     * <code>optional string host = 1;</code>
     */
    String getHost();
    /**
     * <code>optional string host = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    // optional int32 port = 2;
    /**
     * <code>optional int32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 2;</code>
     */
    int getPort();

    // optional .NodeList clients = 3;
    /**
     * <code>optional .NodeList clients = 3;</code>
     */
    boolean hasClients();
    /**
     * <code>optional .NodeList clients = 3;</code>
     */
    NodeList getClients();
    /**
     * <code>optional .NodeList clients = 3;</code>
     */
    NodeListOrBuilder getClientsOrBuilder();

    // optional .NodeList follows = 4;
    /**
     * <code>optional .NodeList follows = 4;</code>
     */
    boolean hasFollows();
    /**
     * <code>optional .NodeList follows = 4;</code>
     */
    NodeList getFollows();
    /**
     * <code>optional .NodeList follows = 4;</code>
     */
    NodeListOrBuilder getFollowsOrBuilder();

    // optional .NodeList leaders = 5;
    /**
     * <code>optional .NodeList leaders = 5;</code>
     */
    boolean hasLeaders();
    /**
     * <code>optional .NodeList leaders = 5;</code>
     */
    NodeList getLeaders();
    /**
     * <code>optional .NodeList leaders = 5;</code>
     */
    NodeListOrBuilder getLeadersOrBuilder();
  }
  /**
   * Protobuf type {@code Node}
   */
  public static final class Node extends
      com.google.protobuf.GeneratedMessage
      implements NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Node(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Node defaultInstance;
    public static Node getDefaultInstance() {
      return defaultInstance;
    }

    public Node getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              host_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readInt32();
              break;
            }
            case 26: {
              NodeList.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = clients_.toBuilder();
              }
              clients_ = input.readMessage(NodeList.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clients_);
                clients_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              NodeList.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = follows_.toBuilder();
              }
              follows_ = input.readMessage(NodeList.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(follows_);
                follows_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              NodeList.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = leaders_.toBuilder();
              }
              leaders_ = input.readMessage(NodeList.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(leaders_);
                leaders_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NodeDto.internal_static_Node_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NodeDto.internal_static_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Node.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Node> PARSER =
        new com.google.protobuf.AbstractParser<Node>() {
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string host = 1;
    public static final int HOST_FIELD_NUMBER = 1;
    private Object host_;
    /**
     * <code>optional string host = 1;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string host = 1;</code>
     */
    public String getHost() {
      Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>optional int32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    // optional .NodeList clients = 3;
    public static final int CLIENTS_FIELD_NUMBER = 3;
    private NodeList clients_;
    /**
     * <code>optional .NodeList clients = 3;</code>
     */
    public boolean hasClients() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .NodeList clients = 3;</code>
     */
    public NodeList getClients() {
      return clients_;
    }
    /**
     * <code>optional .NodeList clients = 3;</code>
     */
    public NodeListOrBuilder getClientsOrBuilder() {
      return clients_;
    }

    // optional .NodeList follows = 4;
    public static final int FOLLOWS_FIELD_NUMBER = 4;
    private NodeList follows_;
    /**
     * <code>optional .NodeList follows = 4;</code>
     */
    public boolean hasFollows() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .NodeList follows = 4;</code>
     */
    public NodeList getFollows() {
      return follows_;
    }
    /**
     * <code>optional .NodeList follows = 4;</code>
     */
    public NodeListOrBuilder getFollowsOrBuilder() {
      return follows_;
    }

    // optional .NodeList leaders = 5;
    public static final int LEADERS_FIELD_NUMBER = 5;
    private NodeList leaders_;
    /**
     * <code>optional .NodeList leaders = 5;</code>
     */
    public boolean hasLeaders() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .NodeList leaders = 5;</code>
     */
    public NodeList getLeaders() {
      return leaders_;
    }
    /**
     * <code>optional .NodeList leaders = 5;</code>
     */
    public NodeListOrBuilder getLeadersOrBuilder() {
      return leaders_;
    }

    private void initFields() {
      host_ = "";
      port_ = 0;
      clients_ = NodeList.getDefaultInstance();
      follows_ = NodeList.getDefaultInstance();
      leaders_ = NodeList.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, clients_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, follows_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, leaders_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, clients_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, follows_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, leaders_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Node prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NodeDto.internal_static_Node_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NodeDto.internal_static_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Node.class, Builder.class);
      }

      // Construct using NodeDto.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClientsFieldBuilder();
          getFollowsFieldBuilder();
          getLeadersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (clientsBuilder_ == null) {
          clients_ = NodeList.getDefaultInstance();
        } else {
          clientsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (followsBuilder_ == null) {
          follows_ = NodeList.getDefaultInstance();
        } else {
          followsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (leadersBuilder_ == null) {
          leaders_ = NodeList.getDefaultInstance();
        } else {
          leadersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NodeDto.internal_static_Node_descriptor;
      }

      public Node getDefaultInstanceForType() {
        return Node.getDefaultInstance();
      }

      public Node build() {
        Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Node buildPartial() {
        Node result = new Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (clientsBuilder_ == null) {
          result.clients_ = clients_;
        } else {
          result.clients_ = clientsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (followsBuilder_ == null) {
          result.follows_ = follows_;
        } else {
          result.follows_ = followsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (leadersBuilder_ == null) {
          result.leaders_ = leaders_;
        } else {
          result.leaders_ = leadersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Node) {
          return mergeFrom((Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Node other) {
        if (other == Node.getDefaultInstance()) return this;
        if (other.hasHost()) {
          bitField0_ |= 0x00000001;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasClients()) {
          mergeClients(other.getClients());
        }
        if (other.hasFollows()) {
          mergeFollows(other.getFollows());
        }
        if (other.hasLeaders()) {
          mergeLeaders(other.getLeaders());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Node) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string host = 1;
      private Object host_ = "";
      /**
       * <code>optional string host = 1;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public String getHost() {
        Object ref = host_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public Builder setHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }

      // optional int32 port = 2;
      private int port_ ;
      /**
       * <code>optional int32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 2;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      // optional .NodeList clients = 3;
      private NodeList clients_ = NodeList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          NodeList, NodeList.Builder, NodeListOrBuilder> clientsBuilder_;
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public boolean hasClients() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public NodeList getClients() {
        if (clientsBuilder_ == null) {
          return clients_;
        } else {
          return clientsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public Builder setClients(NodeList value) {
        if (clientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clients_ = value;
          onChanged();
        } else {
          clientsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public Builder setClients(
          NodeList.Builder builderForValue) {
        if (clientsBuilder_ == null) {
          clients_ = builderForValue.build();
          onChanged();
        } else {
          clientsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public Builder mergeClients(NodeList value) {
        if (clientsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              clients_ != NodeList.getDefaultInstance()) {
            clients_ =
              NodeList.newBuilder(clients_).mergeFrom(value).buildPartial();
          } else {
            clients_ = value;
          }
          onChanged();
        } else {
          clientsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public Builder clearClients() {
        if (clientsBuilder_ == null) {
          clients_ = NodeList.getDefaultInstance();
          onChanged();
        } else {
          clientsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public NodeList.Builder getClientsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getClientsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      public NodeListOrBuilder getClientsOrBuilder() {
        if (clientsBuilder_ != null) {
          return clientsBuilder_.getMessageOrBuilder();
        } else {
          return clients_;
        }
      }
      /**
       * <code>optional .NodeList clients = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          NodeList, NodeList.Builder, NodeListOrBuilder>
          getClientsFieldBuilder() {
        if (clientsBuilder_ == null) {
          clientsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              NodeList, NodeList.Builder, NodeListOrBuilder>(
                  clients_,
                  getParentForChildren(),
                  isClean());
          clients_ = null;
        }
        return clientsBuilder_;
      }

      // optional .NodeList follows = 4;
      private NodeList follows_ = NodeList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          NodeList, NodeList.Builder, NodeListOrBuilder> followsBuilder_;
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public boolean hasFollows() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public NodeList getFollows() {
        if (followsBuilder_ == null) {
          return follows_;
        } else {
          return followsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public Builder setFollows(NodeList value) {
        if (followsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          follows_ = value;
          onChanged();
        } else {
          followsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public Builder setFollows(
          NodeList.Builder builderForValue) {
        if (followsBuilder_ == null) {
          follows_ = builderForValue.build();
          onChanged();
        } else {
          followsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public Builder mergeFollows(NodeList value) {
        if (followsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              follows_ != NodeList.getDefaultInstance()) {
            follows_ =
              NodeList.newBuilder(follows_).mergeFrom(value).buildPartial();
          } else {
            follows_ = value;
          }
          onChanged();
        } else {
          followsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public Builder clearFollows() {
        if (followsBuilder_ == null) {
          follows_ = NodeList.getDefaultInstance();
          onChanged();
        } else {
          followsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public NodeList.Builder getFollowsBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getFollowsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      public NodeListOrBuilder getFollowsOrBuilder() {
        if (followsBuilder_ != null) {
          return followsBuilder_.getMessageOrBuilder();
        } else {
          return follows_;
        }
      }
      /**
       * <code>optional .NodeList follows = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          NodeList, NodeList.Builder, NodeListOrBuilder>
          getFollowsFieldBuilder() {
        if (followsBuilder_ == null) {
          followsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              NodeList, NodeList.Builder, NodeListOrBuilder>(
                  follows_,
                  getParentForChildren(),
                  isClean());
          follows_ = null;
        }
        return followsBuilder_;
      }

      // optional .NodeList leaders = 5;
      private NodeList leaders_ = NodeList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          NodeList, NodeList.Builder, NodeListOrBuilder> leadersBuilder_;
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public boolean hasLeaders() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public NodeList getLeaders() {
        if (leadersBuilder_ == null) {
          return leaders_;
        } else {
          return leadersBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public Builder setLeaders(NodeList value) {
        if (leadersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leaders_ = value;
          onChanged();
        } else {
          leadersBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public Builder setLeaders(
          NodeList.Builder builderForValue) {
        if (leadersBuilder_ == null) {
          leaders_ = builderForValue.build();
          onChanged();
        } else {
          leadersBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public Builder mergeLeaders(NodeList value) {
        if (leadersBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              leaders_ != NodeList.getDefaultInstance()) {
            leaders_ =
              NodeList.newBuilder(leaders_).mergeFrom(value).buildPartial();
          } else {
            leaders_ = value;
          }
          onChanged();
        } else {
          leadersBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public Builder clearLeaders() {
        if (leadersBuilder_ == null) {
          leaders_ = NodeList.getDefaultInstance();
          onChanged();
        } else {
          leadersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public NodeList.Builder getLeadersBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getLeadersFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      public NodeListOrBuilder getLeadersOrBuilder() {
        if (leadersBuilder_ != null) {
          return leadersBuilder_.getMessageOrBuilder();
        } else {
          return leaders_;
        }
      }
      /**
       * <code>optional .NodeList leaders = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          NodeList, NodeList.Builder, NodeListOrBuilder>
          getLeadersFieldBuilder() {
        if (leadersBuilder_ == null) {
          leadersBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              NodeList, NodeList.Builder, NodeListOrBuilder>(
                  leaders_,
                  getParentForChildren(),
                  isClean());
          leaders_ = null;
        }
        return leadersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Node)
    }

    static {
      defaultInstance = new Node(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Node)
  }

  public interface NodeListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Node nodes = 1;
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    java.util.List<Node>
        getNodesList();
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    Node getNodes(int index);
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    java.util.List<? extends NodeOrBuilder>
        getNodesOrBuilderList();
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    NodeOrBuilder getNodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NodeList}
   */
  public static final class NodeList extends
      com.google.protobuf.GeneratedMessage
      implements NodeListOrBuilder {
    // Use NodeList.newBuilder() to construct.
    private NodeList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NodeList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NodeList defaultInstance;
    public static NodeList getDefaultInstance() {
      return defaultInstance;
    }

    public NodeList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NodeList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nodes_ = new java.util.ArrayList<Node>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodes_.add(input.readMessage(Node.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NodeDto.internal_static_NodeList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NodeDto.internal_static_NodeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NodeList.class, Builder.class);
    }

    public static com.google.protobuf.Parser<NodeList> PARSER =
        new com.google.protobuf.AbstractParser<NodeList>() {
      public NodeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeList(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<NodeList> getParserForType() {
      return PARSER;
    }

    // repeated .Node nodes = 1;
    public static final int NODES_FIELD_NUMBER = 1;
    private java.util.List<Node> nodes_;
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    public java.util.List<Node> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    public java.util.List<? extends NodeOrBuilder>
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    public Node getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .Node nodes = 1;</code>
     */
    public NodeOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    private void initFields() {
      nodes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NodeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NodeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NodeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NodeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NodeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NodeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NodeList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NodeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NodeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NodeDto.internal_static_NodeList_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NodeDto.internal_static_NodeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NodeList.class, Builder.class);
      }

      // Construct using NodeDto.NodeList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NodeDto.internal_static_NodeList_descriptor;
      }

      public NodeList getDefaultInstanceForType() {
        return NodeList.getDefaultInstance();
      }

      public NodeList build() {
        NodeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NodeList buildPartial() {
        NodeList result = new NodeList(this);
        int from_bitField0_ = bitField0_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NodeList) {
          return mergeFrom((NodeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NodeList other) {
        if (other == NodeList.getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NodeList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NodeList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Node nodes = 1;
      private java.util.List<Node> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = new java.util.ArrayList<Node>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Node, Node.Builder, NodeOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public java.util.List<Node> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Node getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder setNodes(
          int index, Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder setNodes(
          int index, Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder addNodes(Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder addNodes(
          int index, Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder addNodes(
          Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder addNodes(
          int index, Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder addAllNodes(
          Iterable<? extends Node> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          super.addAll(values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Node.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public NodeOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public java.util.List<? extends NodeOrBuilder>
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Node.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            Node.getDefaultInstance());
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public Node.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, Node.getDefaultInstance());
      }
      /**
       * <code>repeated .Node nodes = 1;</code>
       */
      public java.util.List<Node.Builder>
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Node, Node.Builder, NodeOrBuilder>
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Node, Node.Builder, NodeOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NodeList)
    }

    static {
      defaultInstance = new NodeList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NodeList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NodeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rNodeDto.proto\"v\n\004Node\022\014\n\004host\030\001 \001(\t\022\014\n" +
      "\004port\030\002 \001(\005\022\032\n\007clients\030\003 \001(\0132\t.NodeList\022" +
      "\032\n\007follows\030\004 \001(\0132\t.NodeList\022\032\n\007leaders\030\005" +
      " \001(\0132\t.NodeList\" \n\010NodeList\022\024\n\005nodes\030\001 \003" +
      "(\0132\005.NodeB\tB\007NodeDto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Node_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Node_descriptor,
              new String[] { "Host", "Port", "Clients", "Follows", "Leaders", });
          internal_static_NodeList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NodeList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NodeList_descriptor,
              new String[] { "Nodes", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
