package com.github.liuche51.easyTaskX.dto.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StringListDto.proto

public final class StringListDto {
  private StringListDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StringListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string list = 1;
    /**
     * <code>repeated string list = 1;</code>
     */
    java.util.List<String>
    getListList();
    /**
     * <code>repeated string list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated string list = 1;</code>
     */
    String getList(int index);
    /**
     * <code>repeated string list = 1;</code>
     */
    com.google.protobuf.ByteString
        getListBytes(int index);
  }
  /**
   * Protobuf type {@code StringList}
   */
  public static final class StringList extends
      com.google.protobuf.GeneratedMessage
      implements StringListOrBuilder {
    // Use StringList.newBuilder() to construct.
    private StringList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringList defaultInstance;
    public static StringList getDefaultInstance() {
      return defaultInstance;
    }

    public StringList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new com.google.protobuf.UnmodifiableLazyStringList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StringListDto.internal_static_StringList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StringListDto.internal_static_StringList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StringList.class, Builder.class);
    }

    public static com.google.protobuf.Parser<StringList> PARSER =
        new com.google.protobuf.AbstractParser<StringList>() {
      public StringList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringList(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<StringList> getParserForType() {
      return PARSER;
    }

    // repeated string list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList list_;
    /**
     * <code>repeated string list = 1;</code>
     */
    public java.util.List<String>
        getListList() {
      return list_;
    }
    /**
     * <code>repeated string list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 1;</code>
     */
    public String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 1;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }

    private void initFields() {
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeBytes(1, list_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(list_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static StringList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static StringList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static StringList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static StringList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(StringList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StringList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements StringListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StringListDto.internal_static_StringList_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StringListDto.internal_static_StringList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StringList.class, Builder.class);
      }

      // Construct using StringListDto.StringList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StringListDto.internal_static_StringList_descriptor;
      }

      public StringList getDefaultInstanceForType() {
        return StringList.getDefaultInstance();
      }

      public StringList build() {
        StringList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public StringList buildPartial() {
        StringList result = new StringList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new com.google.protobuf.UnmodifiableLazyStringList(
              list_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.list_ = list_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StringList) {
          return mergeFrom((StringList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StringList other) {
        if (other == StringList.getDefaultInstance()) return this;
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StringList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StringList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string list = 1;
      private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new com.google.protobuf.LazyStringArrayList(list_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public java.util.List<String>
          getListList() {
        return java.util.Collections.unmodifiableList(list_);
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public String getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public com.google.protobuf.ByteString
          getListBytes(int index) {
        return list_.getByteString(index);
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public Builder setList(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public Builder addList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public Builder addAllList(
          Iterable<String> values) {
        ensureListIsMutable();
        super.addAll(values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public Builder clearList() {
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 1;</code>
       */
      public Builder addListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StringList)
    }

    static {
      defaultInstance = new StringList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StringList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StringList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StringList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023StringListDto.proto\"\032\n\nStringList\022\014\n\004l" +
      "ist\030\001 \003(\tB\017B\rStringListDto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_StringList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_StringList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StringList_descriptor,
              new String[] { "List", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
